### ISSUE TITLE
Duplicate Swift/NSColor format entry

### ISSUE THREAD

**Issue by alloy** [Fingertips/ColorPicker#2]
The Swift format for NSColor appears twice in the list of formats, I assume the second one was supposed to be the RubyMotion format?

<img width="465" alt="screen shot 2016-03-30 at 12 28 04" src="https://cloud.githubusercontent.com/assets/2320/14139441/658c72e0-f673-11e5-96c3-b46d750a6c74.png">

**Comment by jeffkreeftmeijer** [comment]
We missed this in 2.0, but this has been fixed in 56a94b5fc99c8e09ee7d6973dbd3163236ecb834. The update should be in the store soon. Thanks!

**Comment by alloy** [comment]
Ace :+1:
